
CREATE TABLE Chat(
    ChatID INT IDENTITY(1,1) NOT NULL,
    ChatUserID1 INT NOT NULL,
    ChatUserID2 INT NOT NULL,
);
ALTER TABLE Chat
ADD CONSTRAINT PK_Chat PRIMARY KEY (ChatID);
GO
ALTER TABLE Chat
ADD CONSTRAINT FK_Chat_User1 FOREIGN KEY (ChatUserID1) REFERENCES Users(UserID);
ALTER TABLE Chat
ADD CONSTRAINT FK_Chat_User2 FOREIGN KEY (ChatUserID2) REFERENCES Users(UserID);
GO


CREATE TABLE Messages(
    MessageID INT IDENTITY(1,1) NOT NULL,
    ChatID INT NOT NULL,
    MessageContent NVARCHAR(20) NOT NULL,
    MessageTimeStamp DATETIME NOT NULL,
    MessageSenderID INT NOT NULL,
);

ALTER TABLE Messages
ADD CONSTRAINT PK_Messages PRIMARY KEY (MessageID);
GO
ALTER TABLE Messages
ADD CONSTRAINT FK_Messages_Chat FOREIGN KEY (ChatID) REFERENCES Chat(ChatID);
ALTER TABLE Messages
ADD CONSTRAINT FK_Messages_Sender FOREIGN KEY (MessageSenderID) REFERENCES Users(UserID);

