name: Build and Release - DB
 
on:
  push:
      
env:
    DOCKER_IMAGE: redgate/flyway
    SCHEMAS: dbo
    MIGRATION_LOCATION: Flyway/migrations
 
    FLYWAY_LICENSE_KEY: ${{ secrets. FW_LICENSE_KEY }}
    FW_USER: ${{ secrets.DB_USERNAME }}
    FW_PASS: ${{ secrets.DB_PASSWORD }}
    FW_URL: ${{ secrets.DB_URL }}

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-20.04         
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
          
      - run: >-           
          docker run --rm
          --volume ${{ github.workspace }}/${{ env.MIGRATION_LOCATION }}:/flyway/sql:ro
          "${{ env.DOCKER_IMAGE }}"
          -licenseKey="${{ env.FLYWAY_LICENSE_KEY }}" 
          -url="${{ env.FW_URL }}"
          -user="${{ env.FW_USER }}"
          -password="${{ env.FW_PASS }}" 
          info -schemas="${{ env.SCHEMAS }}"
      - run: >-
          docker run --rm
          --volume ${{ github.workspace }}/${{ env.MIGRATION_LOCATION }}:/flyway/sql:ro
          "${{ env.DOCKER_IMAGE }}"
          -licenseKey="${{ secrets.FLYWAY_LICENSE_KEY }}" 
          -url="${{ secrets.DB_BUILD_URL }}"
          -user="${{ secrets.DB_BUILD_USERNAME }}"
          -password="${{ secrets.DB_BUILD_PASSWORD }}" 
          migrate -schemas="${{ env.SCHEMAS }}" -outOfOrder=true
      - run: >-
          docker run --rm
          --volume ${{ github.workspace }}/${{ env.MIGRATION_LOCATION }}:/flyway/sql:ro
          "${{ env.DOCKER_IMAGE }}"
          -licenseKey="${{ secrets.FLYWAY_LICENSE_KEY }}" 
          -url="${{ secrets.DB_BUILD_URL }}"
          -user="${{ secrets.DB_BUILD_USERNAME }}"
          -password="${{ secrets.DB_BUILD_PASSWORD }}"
          info -schemas="${{ env.SCHEMAS }}"